pipeline {
    agent any

    stages {
        stage("Git Checkout") {
            steps {
                git(
                  url: 'https://github.com/Saikiran121/VotingApp.git',
                  branch: 'master'
                )
            }
        }

        stage("Greetings") {
            steps {
                echo "Hello, Jenkinsfile!"
            }
        }
    }
}
